### ISSUE TITLE
Help in detail is needed

### ISSUE THREAD

**Issue by warcayac** [loonix/another_xlider#1]
First off, good job with your widget, but your help doc is a bit lacking in depth, IMHO. Simple things like if `values` is an initial value, how and when is used, why it is required. Your code sample can be give certain guide but it cannot be a substitute for written documentation.

This is a humble suggestion only.

**Comment by loonix** [comment]
Hey @warcayac thanks for your input, the current plugin was written by other user that stopped updating it. I have upgraded the plugin to be null safe and to be honest I didn't had an in-depth look at the code.

Please feel free to suggest upgrades/ make PR's to the documentation, if we all help then its better for all.

**Comment by loonix** [comment]
Hey @warcayac I have updated the code and examples feel free to test it out
