### ISSUE TITLE
Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.

### ISSUE THREAD

**Issue by greyovo** [loonix/another_xlider#12]
Error:

/F:/SDK/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/another_xlider-1.1.0/lib/another_xlider.dart:441:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/F:/SDK/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((_) {
                            ^^^^^^^^^^^^^^^^^^^^

**Comment by greyovo** [comment]
I added `?` to `instance` and it works.

```dart
WidgetsBinding.instance?.addPostFrameCallback((_) {
      if (!mounted) {
        return;
      }
      _renderBoxInitialization();
      _arrangeHandlersPosition();
      _drawHatchMark();
      setState(() {});
});
```

**Comment by loonix** [comment]
https://github.com/loonix/another_xlider/pull/9

Changes were made to clear this issue, should be on the latest version

**Comment by greyovo** [comment]
@loonix  It's giving the same error on 1.1.2. I need to modify it manually.

**Comment by loonix** [comment]
It will give you error if you are using flutter 2. Upgrade to v3 and check
