### ISSUE TITLE
Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.

### ISSUE THREAD

**Issue by samnbd** [loonix/another_xlider#15]

**Comment by samnbd** [comment]
This warning is shown using Flutter 3.0 and above

**Comment by LeoAiolia** [comment]
same issue, in flutter 3.0.3

**Comment by loonix** [comment]
Sorry about that guys, as I am using flutter 2.10 I did not notice that issue until now that you flagged. I have approved the PR with that change, will go on the next release.

**Comment by loonix** [comment]
Successfully uploaded https://pub.dev/packages/another_xlider "1.1.2".
