### ISSUE TITLE
Fixed values range

### ISSUE THREAD

**Issue by dlugi57** [loonix/another_xlider#17]
Hi I found the bug. (or I'm just so tired that's not a bug only a feature) 

https://github.com/loonix/another_xlider/blob/a4489d1ccab1b6d548616917a6fb6bf873c9480d/lib/another_xlider.dart#L673

In this condition the actual value is compared to the percents min 0 max 100. Thats why the thow occurs every time when value is bigger than 100 or smaller than 0. You need to calculate the percent of value with the highest fixedValues or compare with _widgetMax and the verify if fixedValues do not contain velues bigger than _widgetMax 

   if (!(widget.fixedValues != null &&
          widget.values[0] >= _widgetMin! &&
          widget.values[0] <= _widgetMax! )) {
        throw 'When using fixedValues, you should set values within the range of fixedValues';
      }

the same for the range slider

**Comment by dlugi57** [comment]
Sorry! 
Like allways I read the documentation at the end 

"Fixed Values 
If you want to have an array of fixed items and slide through it, you can use fixedValues property. use FlutterSliderFixedValue to add your fixed values.
FlutterSliderFixedValue has following properties:

percent: (int) ( between 0..100 inclusive). the position of fixed item
value: (dynamic) the value of fixed item
when using fixedValues, values of values property, must be within 0..100"

**Comment by loonix** [comment]
Was your issue solved, sorry only had time now to have a look at this

**Comment by dlugi57** [comment]
I could resolve this in another way but I think that limitation from 0 to 100 in this option is too "limited"

**Comment by loonix** [comment]
I think its fair to be 100, but what do you suggest?

**Comment by loonix** [comment]
since I did not get more info on this I am closing the issue
