### ISSUE TITLE
Set Initial Value

### ISSUE THREAD

**Issue by awais-amjed** [loonix/another_xlider#18]
Is there a way to set the initial value of the slider?

**Comment by loonix** [comment]
Have you tried to set the values?

var yourvalue = 100;

`FlutterSlider(
  values: [yourvalue],
  max: 500,
  min: 0,`

**Comment by awais-amjed** [comment]
I actually tried it yesterday by giving it a value as you suggested, but it didn't work. But today I gave it a percentage and it worked. Thanks for the reply 🤗

**Comment by awais-amjed** [comment]
I checked and if you are not using fixed values, then your method works, but if we are using fixed values then you have to give a percentage in values: [percentage]
