### ISSUE TITLE
Handler start and end position

### ISSUE THREAD

**Issue by callmejm** [loonix/another_xlider#2]
![image](https://user-images.githubusercontent.com/6957533/143203044-0af3124a-703f-4628-87ca-09b375dc09b8.png)

How to set the handler start and end position is between trackbar ? Now is offset

**Comment by loonix** [comment]
Hi,

the example is on the readme:

> Range Slider
> A simple example of range slider
```dart
FlutterSlider(
  values: [30, 420],
  rangeSlider: true,
  max: 500,
  min: 0,
  onDragging: (handlerIndex, lowerValue, upperValue) {
    _lowerValue = lowerValue;
    _upperValue = upperValue;
    setState(() {});
  },
)
```
