### ISSUE TITLE
Is there a way to make the handler on the left fit the container?

### ISSUE THREAD

**Issue by CaoAnhDev** [loonix/another_xlider#26]
<img width="336" alt="Screenshot 2023-06-14 at 10 27 44 AM" src="https://github.com/loonix/another_xlider/assets/122242935/df8007ef-5647-4b54-9f79-cf48850f9416">

Hi, as you can see above, the handler on the right side looks good, but the left side is not close to the container. Is there a way to fix it?

Thank you!

**Comment by loonix** [comment]
Please share the code example and I will have a look later
