### ISSUE TITLE
How can I remove the padding around the trackbar?

### ISSUE THREAD

**Issue by desmeit** [loonix/another_xlider#27]
There is a padding around the trackbar (blue area). How can I disable it?

![Bildschirmfoto 2023-06-20 um 17 17 35](https://github.com/loonix/another_xlider/assets/9454529/d2229b22-2ce0-4d2d-a6be-b500cfe6c337)

**Comment by FreeMrQ** [comment]
same question +1

**Comment by ChrisElliotUK** [comment]
I've opened a pull request for this, it introduces a new param `containerHeightFactor` which will allow you to effectively reduce the padding. #29 

ps. I also added type safety as I am not a fan of dynamic! It may cause a few errors but you can either remove it on a new branch or add types to your slider.

**Comment by loonix** [comment]
merged, will try soon to release this. Thanks to everyone.
