### ISSUE TITLE
_stopHandlerAnimation should stop force unwrapping potentially null parameters

### ISSUE THREAD

**Issue by john-paradym** [loonix/another_xlider#31]
Seeing occasional crashes on line 1686 in another_xlider.dart when it's trying to force unwrap a null object i.e. 

`controller!.reset();`

Obviously controller (and animation) can be passed in as null, so the function should check for this

If I get time, I'll try submitting a pull request to fix this, but wanted to capture this as an issue

Thanks
John

**Comment by loonix** [comment]
Thanks John, that would be great

**Comment by loonix** [comment]
Change is now on 3.0.2 and should be in pub.dev, thanks
