### ISSUE TITLE
Is this a replacement for flutter_xlider?

### ISSUE THREAD

**Issue by pamafe1976** [loonix/another_xlider#37]
Hi, 

Since this package looks like a fork of flutter_xlider, I was wondering if the original package is known to be no longer mantained.

Regards

**Comment by loonix** [comment]
Hi, it's based on the xlider, as it says at the end of the readme file. The original plugin seems to not be maintained since 1 year ago. There are quite some PRs there which I merged here...

**Comment by loonix** [comment]
Feel free to contribute to the project.. I don't have much time to maintain it but PRs are welcome
