### ISSUE TITLE
Dragging when selectByTap is false

### ISSUE THREAD

**Issue by dev4jam** [loonix/another_xlider#7]
Hi! Thanks for supporting this component. It's super useful! 

I have encountered one issue: when I set selectByTap to false I still can tap on the slider outside of the handlebar and it jumps to this position. Is it possible to specify behavior when only if user drags the handlebar then it changes it's position and calls all dragging related callbacks? 

The problem actually comes from UI where we have multiple sliders in the list and when user tries to scroll through the list of these sliders they start changing values although user triggered scrolling by tapping outside of handlebars.

**Comment by loonix** [comment]
Hey, if possible please give me a code example so I can quickly have a look at the issue. If you in the meantime find a fix for it feel free to make a Pull request

**Comment by dev4jam** [comment]
Here is the minimal [project to reproduce](https://drive.google.com/file/d/1udvE3ST2an6FHbB942PUQf3gfoWr6hwQ/view?usp=sharing). Notice how hard it is to scroll through them. I'm digging the sources and currently haven't found the solution yet.

**Comment by loonix** [comment]
Found any solution for this issue?

**Comment by loonix** [comment]
No answer closing the issue
